name: IMDN
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch::pytorch=1.12.1
  - pytorch::torchvision=0.13.1
  - conda-forge::cudatoolkit=11.3
  - conda-forge::scikit-image
  - conda-forge::opencv
  - pip
  - pip:
    - fire
    - gdown
